Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "cucumber")
Ingredient.create(name: "straberry")
Ingredient.create(name: "banana")
Ingredient.create(name: "orange")
